services:
  master_0:
    image: bitnami/mysql:latest
    environment:
      MYSQL_REPLICATION_MODE: master
      MYSQL_DATABASE: order_db
      MYSQL_REPLICATION_USER: repl_user
      MYSQL_REPLICATION_PASSWORD: 12345678
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - master_0:/bitnami/mysql/data
      - master_0_init_scripts:/docker-entrypoint-initdb.d
    restart: always

  slave_0_0:
    image: bitnami/mysql:latest
    depends_on:
      - master_0
    environment:
      MYSQL_REPLICATION_MODE: slave
      MYSQL_REPLICATION_USER: repl_user
      MYSQL_REPLICATION_PASSWORD: 12345678
      MYSQL_MASTER_HOST: master_0
      MYSQL_MASTER_PORT_NUMBER: 3306
      MYSQL_MASTER_ROOT_PASSWORD: 123456
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - slave_0_0:/bitnami/mysql/data
    restart: always

  slave_0_1:
    image: bitnami/mysql:latest
    depends_on:
      - master_0
    environment:
      MYSQL_REPLICATION_MODE: slave
      MYSQL_REPLICATION_USER: repl_user
      MYSQL_REPLICATION_PASSWORD: 12345678
      MYSQL_MASTER_HOST: master_0
      MYSQL_MASTER_PORT_NUMBER: 3306
      MYSQL_MASTER_ROOT_PASSWORD: 123456
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - "3308:3306"
    volumes:
      - slave_0_1:/bitnami/mysql/data
    restart: always

  master_1:
    image: bitnami/mysql:latest
    environment:
      MYSQL_REPLICATION_MODE: master
      MYSQL_DATABASE: order_db
      MYSQL_REPLICATION_USER: repl_user
      MYSQL_REPLICATION_PASSWORD: 12345678
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - "3316:3306"
    volumes:
      - master_1:/bitnami/mysql/data
      - master_1_init_scripts:/docker-entrypoint-initdb.d
    restart: always

  slave_1_0:
    image: bitnami/mysql:latest
    depends_on:
      - master_1
    environment:
      MYSQL_REPLICATION_MODE: slave
      MYSQL_REPLICATION_USER: repl_user
      MYSQL_REPLICATION_PASSWORD: 12345678
      MYSQL_MASTER_HOST: master_1
      MYSQL_MASTER_PORT_NUMBER: 3306
      MYSQL_MASTER_ROOT_PASSWORD: 123456
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - "3317:3306"
    volumes:
      - slave_1_0:/bitnami/mysql/data
    restart: always

  slave_1_1:
    image: bitnami/mysql:latest
    depends_on:
      - master_1
    environment:
      MYSQL_REPLICATION_MODE: slave
      MYSQL_REPLICATION_USER: repl_user
      MYSQL_REPLICATION_PASSWORD: 12345678
      MYSQL_MASTER_HOST: master_1
      MYSQL_MASTER_PORT_NUMBER: 3306
      MYSQL_MASTER_ROOT_PASSWORD: 123456
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - "3318:3306"
    volumes:
      - slave_1_1:/bitnami/mysql/data
    restart: always

  zookeeper:
    image: zookeeper:latest
    container_name: zookeeper_container
    ports:
      - "2181:2181"
    environment:
      ZOO_TICK_TIME: 2000
      ZOO_INIT_LIMIT: 10
      ZOO_SYNC_LIMIT: 5
      ZOO_CLIENT_PORT: 2181
    volumes:
      - zookeeper_data:/data/zookeeper
    restart: always

volumes:
  master_0:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: C:/Study/docker_configs/mysql/master_0/data/
  slave_0_0:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: C:/Study/docker_configs/mysql/slave_0_0/data/
  slave_0_1:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: C:/Study/docker_configs/mysql/slave_0_1/data/
  master_1:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: C:/Study/docker_configs/mysql/master_1/data/
  slave_1_0:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: C:/Study/docker_configs/mysql/slave_1_0/data/
  slave_1_1:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: C:/Study/docker_configs/mysql/slave_1_1/data/
  zookeeper_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: C:/Study/docker_configs/zookeeper/data/

  master_0_init_scripts:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: C:/Study/docker_configs/mysql/master_0/init_scripts/

  master_1_init_scripts:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: C:/Study/docker_configs/mysql/master_1/init_scripts/
